version: "3.8"

services:
  api:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    container_name: "api"
    env_file:
      - ./.env.dev
    volumes:
      - ./:/src/
    tty: true
    ports:
      - "8080:8080"
    networks:
      - web
  db:
    image: mysql:8.0
    container_name: db
    env_file:
      - ./db/.env.dev
    volumes:
      - data:/var/lib/mysql
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./db/initdb.d:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    tty: true
    networks:
      - web

volumes:
  data:
networks:
  web:

