version: '3'
services:
  next:
    build:
      context: .
      dockerfile: Dockerfile.prod
    # volumes:
      # - .:/usr/src/app
    # command: bash -c " npm run build && npm run start"
    ports:
      - "3000:3000"
    networks:
      - api_web
networks:
  api_web:
    external: true