FROM python:3.9-slim-buster

WORKDIR /src

# 必要なシステムパッケージをインストール
RUN apt-get update


RUN pip install --upgrade pip

RUN pip install poetry
# 仮想環境をたてない
RUN poetry config virtualenvs.create false

VOLUME ["/tmp/gunicorn_socket"]


# アプリケーションの依存関係をインストール
COPY . .
RUN poetry install

EXPOSE 8080

# TCP
CMD ["gunicorn", "api.mysql_article:app", "-c", "./api/config/gunicorn.py"]

# UNIX domain socket
# CMD ["gunicorn", "api.mysql_article:app", "-c", "api/config/gunicorn.conf.py"]
